#!/bin/bash

# Exit on first failing command.
set -e
# Echo commands to console.
set -x

IMAGE_NAME="firestore-emulator"
CONTAINER_NAME="firestore-emulator"
PORT="8080"
FIRESTORE_PROJECT_ID="dummy-project-id"

docker version

# Clear any previous container.
docker rm -f "$CONTAINER_NAME" || true

docker build \
  --tag "$IMAGE_NAME" \
  .

docker run \
  --name "$CONTAINER_NAME" \
  --detach \
  --env "FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}" \
  --env "PORT=${PORT}" \
  --publish "${PORT}:${PORT}" \
  "$IMAGE_NAME"

# Basic test to see if the emulator started.
wget -qO- "http://localhost:${PORT}/v1/projects/${FIRESTORE_PROJECT_ID}/databases/(default)/documents/dummy-document"

docker rm -f "$CONTAINER_NAME"